import { Setup, TimeSegment } from './types';

// Utilities to convert time string "HH:MM" to minutes
export const timeToMin = (time: string): number => {
  const [h, m] = time.split(':').map(Number);
  return h * 60 + m;
};

// Global config
export const START_OF_DAY = timeToMin('04:00');
export const END_OF_DAY = timeToMin('20:00'); // 8 PM
export const MARKET_OPEN = timeToMin('09:30');
export const MARKET_CLOSE = timeToMin('16:00');

export const TIME_SEGMENTS: TimeSegment[] = [
  {
    name: 'Pre-Market',
    start: START_OF_DAY,
    end: MARKET_OPEN,
    color: 'bg-indigo-900/30 border-indigo-500/30',
    label: 'PRE',
  },
  {
    name: 'Open',
    start: MARKET_OPEN,
    end: timeToMin('10:30'),
    color: 'bg-emerald-900/30 border-emerald-500/30',
    label: 'OPEN',
  },
  {
    name: 'Morning',
    start: timeToMin('10:30'),
    end: timeToMin('12:00'),
    color: 'bg-blue-900/30 border-blue-500/30',
    label: 'AM',
  },
  {
    name: 'Midday',
    start: timeToMin('12:00'),
    end: timeToMin('14:00'),
    color: 'bg-gray-800/50 border-gray-600/30',
    label: 'LUNCH',
  },
  {
    name: 'Power Hour',
    start: timeToMin('14:00'),
    end: MARKET_CLOSE,
    color: 'bg-amber-900/30 border-amber-500/30',
    label: 'PWR',
  },
  {
    name: 'After Hours',
    start: MARKET_CLOSE,
    end: END_OF_DAY,
    color: 'bg-purple-900/30 border-purple-500/30',
    label: 'POST',
  },
];

export const SETUPS: Setup[] = [
  {
    id: 1,
    name: 'News Momentum Play',
    type: 'Long',
    description:
      'High relative volume reaction to fresh catalysts in pre-market.',
    startTime: timeToMin('07:00'),
    endTime: timeToMin('09:00'),
    risk: 'High',
    category: 'Momentum',
  },
  {
    id: 2,
    name: 'Pop and Drop',
    type: 'Short',
    description: 'Fading the initial spike on press releases.',
    startTime: timeToMin('07:00'),
    endTime: timeToMin('09:30'),
    risk: 'Medium',
    category: 'Reversal',
  },
  {
    id: 3,
    name: 'Opening Range Breakout (ORB)',
    type: 'Long',
    description: 'Break of the high established in the first 5-15/30 mins.',
    startTime: timeToMin('09:30'),
    endTime: timeToMin('10:00'),
    risk: 'Medium',
    category: 'Breakout',
  },
  {
    id: 4,
    name: 'Gap Up Short',
    type: 'Short',
    description: 'Fading a gap up that lacks volume support at the bell.',
    startTime: timeToMin('09:30'),
    endTime: timeToMin('10:00'),
    risk: 'High',
    category: 'Reversal',
  },
  {
    id: 8,
    name: 'Panic Dip Buy',
    type: 'Long',
    description: 'Catching the washout flush at the open.',
    startTime: timeToMin('09:30'),
    endTime: timeToMin('10:30'),
    risk: 'High',
    category: 'Reversal',
  },
  {
    id: 13,
    name: 'Overextended Gap Up Short',
    type: 'Short',
    description: 'Shorting a multi-day runner gapping up on exhaustion.',
    startTime: timeToMin('09:30'),
    endTime: timeToMin('10:15'),
    risk: 'Medium',
    category: 'Mean Reversion',
  },
  {
    id: 14,
    name: 'Overextended Gap Down Long',
    type: 'Long',
    description: 'Buying a stock gapping down into major support.',
    startTime: timeToMin('09:30'),
    endTime: timeToMin('10:15'),
    risk: 'Medium',
    category: 'Mean Reversion',
  },
  {
    id: 7,
    name: 'Parabolic Short (AM)',
    type: 'Short',
    description:
      'Shorting a vertical move that violates statistical deviations.',
    startTime: timeToMin('09:45'),
    endTime: timeToMin('11:00'),
    risk: 'High',
    category: 'Reversal',
  },
  {
    id: 17,
    name: 'Liquidity Trap',
    type: 'Both',
    description:
      'Identifying false breakouts/breakdowns designed to grab stops.',
    startTime: timeToMin('09:30'),
    endTime: timeToMin('11:00'),
    risk: 'High',
    category: 'Structure',
  },
  {
    id: 15,
    name: 'VWAP Bounce',
    type: 'Long',
    description: 'Pullback to Volume Weighted Average Price in an uptrend.',
    startTime: timeToMin('10:00'),
    endTime: timeToMin('15:30'),
    risk: 'Low',
    category: 'Trend',
  },
  {
    id: 16,
    name: 'VWAP Rejection',
    type: 'Short',
    description: 'Rally into VWAP failing in a downtrend.',
    startTime: timeToMin('10:00'),
    endTime: timeToMin('15:30'),
    risk: 'Low',
    category: 'Trend',
  },
  {
    id: 5,
    name: 'Afternoon Breakout',
    type: 'Long',
    description: 'Break of midday consolidation range.',
    startTime: timeToMin('11:00'),
    endTime: timeToMin('14:00'),
    risk: 'Medium',
    category: 'Breakout',
  },
  {
    id: 6,
    name: 'Afternoon Fade',
    type: 'Short',
    description: 'Slow bleed of a stock that failed to hold morning gains.',
    startTime: timeToMin('11:30'),
    endTime: timeToMin('16:00'),
    risk: 'Low',
    category: 'Trend',
  },
  {
    id: 72,
    name: 'Parabolic Short (PM)',
    type: 'Short',
    description: 'Shorting late day squeezes.',
    startTime: timeToMin('14:00'),
    endTime: timeToMin('16:00'),
    risk: 'High',
    category: 'Reversal',
  },
  {
    id: 18,
    name: 'Earnings Play (Post)',
    type: 'Both',
    description: 'Trading immediate reaction to earnings release.',
    startTime: timeToMin('16:00'),
    endTime: timeToMin('16:30'),
    risk: 'High',
    category: 'Event',
  },
  {
    id: 182,
    name: 'Earnings Play (Pre)',
    type: 'Both',
    description: 'Trading immediate reaction to earnings release.',
    startTime: timeToMin('08:00'),
    endTime: timeToMin('09:30'),
    risk: 'High',
    category: 'Event',
  },
  // All Day / Context dependent setups mapped to core trading hours for visualization
  {
    id: 9,
    name: 'First Green Day',
    type: 'Long',
    description: 'Reversal day after parabolic down move (Daily setup).',
    startTime: timeToMin('09:30'),
    endTime: timeToMin('16:00'),
    risk: 'Medium',
    category: 'Structure',
  },
  {
    id: 10,
    name: 'First Red Day',
    type: 'Short',
    description: 'Reversal day after multi-day run (Daily setup).',
    startTime: timeToMin('09:30'),
    endTime: timeToMin('16:00'),
    risk: 'Medium',
    category: 'Structure',
  },
  {
    id: 11,
    name: 'Reverse Split Long',
    type: 'Long',
    description: 'Float compression play after reverse split.',
    startTime: timeToMin('09:30'),
    endTime: timeToMin('16:00'),
    risk: 'High',
    category: 'Event',
  },
  {
    id: 12,
    name: 'Reverse Split Short',
    type: 'Short',
    description: 'Dilution anticipation on bad companies.',
    startTime: timeToMin('09:30'),
    endTime: timeToMin('16:00'),
    risk: 'Medium',
    category: 'Event',
  },
  {
    id: 19,
    name: 'Episodic Pivot',
    type: 'Both',
    description: 'Fundamental change driving a new trend.',
    startTime: timeToMin('09:30'),
    endTime: timeToMin('16:00'),
    risk: 'Medium',
    category: 'Trend',
  },
];
