/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseIndexRouteImport } from './routes/course/index'
import { Route as CourseNotesRouteImport } from './routes/course/notes'
import { Route as CourseLibraryRouteImport } from './routes/course/library'
import { Route as CourseLibraryIndexRouteImport } from './routes/course/library/index'
import { Route as CourseModuleSlugLessonSlugRouteImport } from './routes/course/$moduleSlug.$lessonSlug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as CourseLibraryModuleSlugLessonSlugRouteImport } from './routes/course/library/$moduleSlug.$lessonSlug'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseNotesRoute = CourseNotesRouteImport.update({
  id: '/course/notes',
  path: '/course/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseLibraryRoute = CourseLibraryRouteImport.update({
  id: '/course/library',
  path: '/course/library',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseLibraryIndexRoute = CourseLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseLibraryRoute,
} as any)
const CourseModuleSlugLessonSlugRoute =
  CourseModuleSlugLessonSlugRouteImport.update({
    id: '/course/$moduleSlug/$lessonSlug',
    path: '/course/$moduleSlug/$lessonSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseLibraryModuleSlugLessonSlugRoute =
  CourseLibraryModuleSlugLessonSlugRouteImport.update({
    id: '/$moduleSlug/$lessonSlug',
    path: '/$moduleSlug/$lessonSlug',
    getParentRoute: () => CourseLibraryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/course/library': typeof CourseLibraryRouteWithChildren
  '/course/notes': typeof CourseNotesRoute
  '/course': typeof CourseIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/course/$moduleSlug/$lessonSlug': typeof CourseModuleSlugLessonSlugRoute
  '/course/library/': typeof CourseLibraryIndexRoute
  '/course/library/$moduleSlug/$lessonSlug': typeof CourseLibraryModuleSlugLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/course/notes': typeof CourseNotesRoute
  '/course': typeof CourseIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/course/$moduleSlug/$lessonSlug': typeof CourseModuleSlugLessonSlugRoute
  '/course/library': typeof CourseLibraryIndexRoute
  '/course/library/$moduleSlug/$lessonSlug': typeof CourseLibraryModuleSlugLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/course/library': typeof CourseLibraryRouteWithChildren
  '/course/notes': typeof CourseNotesRoute
  '/course/': typeof CourseIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/course/$moduleSlug/$lessonSlug': typeof CourseModuleSlugLessonSlugRoute
  '/course/library/': typeof CourseLibraryIndexRoute
  '/course/library/$moduleSlug/$lessonSlug': typeof CourseLibraryModuleSlugLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/support'
    | '/course/library'
    | '/course/notes'
    | '/course'
    | '/api/stripe/webhook'
    | '/course/$moduleSlug/$lessonSlug'
    | '/course/library/'
    | '/course/library/$moduleSlug/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/support'
    | '/course/notes'
    | '/course'
    | '/api/stripe/webhook'
    | '/course/$moduleSlug/$lessonSlug'
    | '/course/library'
    | '/course/library/$moduleSlug/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/support'
    | '/course/library'
    | '/course/notes'
    | '/course/'
    | '/api/stripe/webhook'
    | '/course/$moduleSlug/$lessonSlug'
    | '/course/library/'
    | '/course/library/$moduleSlug/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SupportRoute: typeof SupportRoute
  CourseLibraryRoute: typeof CourseLibraryRouteWithChildren
  CourseNotesRoute: typeof CourseNotesRoute
  CourseIndexRoute: typeof CourseIndexRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  CourseModuleSlugLessonSlugRoute: typeof CourseModuleSlugLessonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/': {
      id: '/course/'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/notes': {
      id: '/course/notes'
      path: '/course/notes'
      fullPath: '/course/notes'
      preLoaderRoute: typeof CourseNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/library': {
      id: '/course/library'
      path: '/course/library'
      fullPath: '/course/library'
      preLoaderRoute: typeof CourseLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/library/': {
      id: '/course/library/'
      path: '/'
      fullPath: '/course/library/'
      preLoaderRoute: typeof CourseLibraryIndexRouteImport
      parentRoute: typeof CourseLibraryRoute
    }
    '/course/$moduleSlug/$lessonSlug': {
      id: '/course/$moduleSlug/$lessonSlug'
      path: '/course/$moduleSlug/$lessonSlug'
      fullPath: '/course/$moduleSlug/$lessonSlug'
      preLoaderRoute: typeof CourseModuleSlugLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/library/$moduleSlug/$lessonSlug': {
      id: '/course/library/$moduleSlug/$lessonSlug'
      path: '/$moduleSlug/$lessonSlug'
      fullPath: '/course/library/$moduleSlug/$lessonSlug'
      preLoaderRoute: typeof CourseLibraryModuleSlugLessonSlugRouteImport
      parentRoute: typeof CourseLibraryRoute
    }
  }
}

interface CourseLibraryRouteChildren {
  CourseLibraryIndexRoute: typeof CourseLibraryIndexRoute
  CourseLibraryModuleSlugLessonSlugRoute: typeof CourseLibraryModuleSlugLessonSlugRoute
}

const CourseLibraryRouteChildren: CourseLibraryRouteChildren = {
  CourseLibraryIndexRoute: CourseLibraryIndexRoute,
  CourseLibraryModuleSlugLessonSlugRoute:
    CourseLibraryModuleSlugLessonSlugRoute,
}

const CourseLibraryRouteWithChildren = CourseLibraryRoute._addFileChildren(
  CourseLibraryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SupportRoute: SupportRoute,
  CourseLibraryRoute: CourseLibraryRouteWithChildren,
  CourseNotesRoute: CourseNotesRoute,
  CourseIndexRoute: CourseIndexRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  CourseModuleSlugLessonSlugRoute: CourseModuleSlugLessonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
