/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseIndexRouteImport } from './routes/course/index'
import { Route as CourseModuleSlugLessonSlugRouteImport } from './routes/course/$moduleSlug.$lessonSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseModuleSlugLessonSlugRoute =
  CourseModuleSlugLessonSlugRouteImport.update({
    id: '/course/$moduleSlug/$lessonSlug',
    path: '/course/$moduleSlug/$lessonSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course': typeof CourseIndexRoute
  '/course/$moduleSlug/$lessonSlug': typeof CourseModuleSlugLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course': typeof CourseIndexRoute
  '/course/$moduleSlug/$lessonSlug': typeof CourseModuleSlugLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/course/': typeof CourseIndexRoute
  '/course/$moduleSlug/$lessonSlug': typeof CourseModuleSlugLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/course' | '/course/$moduleSlug/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/course' | '/course/$moduleSlug/$lessonSlug'
  id: '__root__' | '/' | '/course/' | '/course/$moduleSlug/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseIndexRoute: typeof CourseIndexRoute
  CourseModuleSlugLessonSlugRoute: typeof CourseModuleSlugLessonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/': {
      id: '/course/'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$moduleSlug/$lessonSlug': {
      id: '/course/$moduleSlug/$lessonSlug'
      path: '/course/$moduleSlug/$lessonSlug'
      fullPath: '/course/$moduleSlug/$lessonSlug'
      preLoaderRoute: typeof CourseModuleSlugLessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseIndexRoute: CourseIndexRoute,
  CourseModuleSlugLessonSlugRoute: CourseModuleSlugLessonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
